import React from 'react';
import { NextPageContext } from 'next';
import { getSession } from 'next-auth/react';
import Head from "next/head";
import Navbar from '@/components/Navbar';
import Billboard from '@/components/Billboard';
import MovieList from '@/components/MovieList';
import InfoModal from '@/components/InfoModal';
import useMovieList from '@/hooks/useMovieList';
import useFavorites from '@/hooks/useFavorites';
import useInfoModalStore from '@/hooks/useInfoModalStore';

// render this on server side, because of data fetching, its the properly solution

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  }
}

const Home = () => {

  // Movielist, favorites films

  const { data: movies = [] } = useMovieList();
  const { data: favorites = [] } = useFavorites();

  // Info modal
  
  const {isOpen, closeModal} = useInfoModalStore();

  return (
    <>
    <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" type="image/png" href="film.png"/>
      </Head>
      <InfoModal visible={isOpen} onClose={closeModal}/>
      <Navbar/>
      <Billboard/>
      <div className="pb-40">
        <MovieList title="Trending Now" data={movies}/>
        <MovieList title="My List" data={favorites}/>
      </div>
    </>
  );
};

export default Home;
